# Generated by Django 4.2 on 2023-04-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='seller',
            new_name='user',
        ),
    ]
